### PR TITLE
chore: Upgrade clap from v3 to v4

### LINKED ISSUE #52: Update clap to v4
**Is your feature request related to a problem? Please describe.**

```sh
$ cargo outdated

Name           Project  Compat   Latest   Kind    Platform
----           -------  ------   ------   ----    --------
clap           3.2.23   ---      4.0.32   Normal  ---
clap_complete  3.2.5    ---      4.0.7    Normal  --
```

**Describe the solution you'd like**

Update `clap` and `clap_complete` to the latest version.

**Describe alternatives you've considered**
None.

**Additional context**
Changelog: https://github.com/clap-rs/clap/blob/master/CHANGELOG.md

### PR DESCRIPTION
**Pull request by anas-elgarhy**
## Description
Upgrade the `clap` crate version from `3.2.23` to `4.2.7` and the `clap_complete` crate version from `3.2.5` to `4.2.3` (the latest versions at this time).
> To make this work I had to make some weird* decisions (if we can say), like implementing the `FromStr` crate for the `Color` struct to use it as a custom parser for the colour option, and making the `parse_dir` return `Result<String, String>` instead of just return a `String` 'cause the `value_parser` attr require a function that returns a Result type. Am not sure if this is the best solution in the world to solve this problem, but it works :) 

## Motivation and Context
- Close #52 

## How Has This Been Tested?
- I ran the `cargo run -- --help`  command and  I saw the expected output
- I ran the all tests and they passed

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have formatted the code with [rustfmt](https://github.com/rust-lang/rustfmt).
- [x] I checked the lints with [clippy](https://github.com/rust-lang/rust-clippy).

### CODE REVIEW

**Comment by anas-elgarhy** [comment]
Sorry, but I noticed that I caused casting issues at the runtime like this when I try to use the `--select` option
```log
thread 'main' panicked at 'Mismatch between definition and access of `select`. Could not downcast to gpg_tui::app::selection::Selection, need to downcast to alloc::string::String
', src/args.rs:86:17
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4a59ba4d54a3ec0d8ea1e82b7eeb5c8b0162de04/library/std/src/panicking.rs:578:5
   1: core::panicking::panic_fmt
             at /rustc/4a59ba4d54a3ec0d8ea1e82b7eeb5c8b0162de04/library/core/src/panicking.rs:67:14
   2: clap_builder::parser::error::MatchesError::unwrap
             at /home/anas/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.2.7/src/parser/error.rs:32:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
zsh: IOT instruction (core dumped)  RUST_BACKTRACE=1 cargo run -- --select row1
```
So I mark this PR as a draft until I solve the issue

**Comment by anas-elgarhy** [comment]
I had to change the `--select` option values a little bit to make me able to derive the `ValueEnum` trait and fix the issue, but it's still compatible with the previous version thanks to the aliases

**Comment by anas-elgarhy** [comment]
Hi @orhun I hope you are well, please don't forget to review this PR when u have free time.

**Comment by orhun** [comment]
Hey, sorry, I've been extremely busy and just got the time to review this PR. There seems to be a build failure, can you look into it?

**Comment by orhun** [comment]
I tested this and there is one incompatibility with the old version:

```
--select <option>       Enables the selection mode [env: SELECT=] [possible values: row1, row2, key, key-id, key-fingerprint, key-user-id]
```

Whereas, it was:

```
--select <option>         Enables the selection mode [env: SELECT=] [possible values: key_id, key_fpr, user_id, row1, row2]
```

In this case, `gpg-tui --select key_fpr` does not work:

```
error: invalid value 'key_fpr' for '--select <option>'
  [possible values: row1, row2, key, key-id, key-fingerprint, key-user-id]

  tip: a similar value exists: 'key'

For more information, try '--help'.
```

**Comment by anas-elgarhy** [comment]
I think I fixed the issue, did you've any other notes?

**Pull request merged**
