### PR TITLE
Add Wayland clipboard support

### PR DESCRIPTION
**Pull request by timvisee**
## Description
This adds clipboard support for Wayland. This makes `copypasta-ext` [choose](https://docs.rs/copypasta-ext/0.3.7/copypasta_ext/display/enum.DisplayServer.html#method.select) the appropriate clipboard provider at runtime, so the Wayland context is selected when needed (which uses [`wl-copy`/`wl-paste`](https://docs.rs/copypasta-ext/0.3.7/copypasta_ext/wayland_bin/index.html)). This even enables clipboard support on Windows/macOS if `gpg-tui` will ever support these.

Note that, due to new `copypasta` requirements, this also bumps the MSRV from 1.46.0 to 1.47.0. I've updated the README accordingly.

## Motivation and Context
Wayland support!

## How Has This Been Tested?
- Binary with clipboard features manually tested on development machine.
- `cargo test`

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (no code change)
- [x] Refactor (refactoring production code)

## Checklist:
- [x] My code follows the code style of this project.
- [x] I have updated the documentation accordingly.
- [x] I have formatted the code with [rustfmt](https://github.com/rust-lang/rustfmt).
- [x] I checked the lints with [clippy](https://github.com/rust-lang/rust-clippy).
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by timvisee** [comment]
It seems a [workflow](https://github.com/orhun/gpg-tui/pull/30/checks?check_run_id=3154906078) fails. But I don't think it's caused by these changes.

**Comment by orhun** [comment]
> It seems a [workflow](https://github.com/orhun/gpg-tui/pull/30/checks?check_run_id=3154906078) fails. But I don't think it's caused by these changes.

Yes, no problem. I have to fix it (somehow) for further contributions/PRs though.

**Comment by orhun** [comment]
Does `DisplayServer::try_context` return `x11_fork` by default on X11 if no feature is specified in `Cargo.toml`?

https://gitlab.com/timvisee/copypasta-ext/-/blob/a0dae103c7723571a4c2577d29645bd02d4b9f2b/src/display.rs#L66

Asking just to confirm.

**Comment by timvisee** [comment]
> Does `DisplayServer::try_context` return `x11_fork` by default on X11 if no feature is specified in `Cargo.toml`?
> 
> https://gitlab.com/timvisee/copypasta-ext/-/blob/a0dae103c7723571a4c2577d29645bd02d4b9f2b/src/display.rs#L66
> 
> Asking just to confirm.

It defaults to `["x11-bin", "x11-fork", "wayland-bin"]` (see [Cargo.toml](https://gitlab.com/timvisee/copypasta-ext/-/blob/a0dae103c7723571a4c2577d29645bd02d4b9f2b/Cargo.toml#L18)), in which case it returns `x11_fork` with X11. This is what it currently does.

If you explicitly set to use no features (`default-features = false`), it does return `None` on X11.

As you may have noticed, `x11-bin` isn't needed because it always prefers the forking provider. So you may even change the dependency to the following, though this won't decrease the number of dependencies:

```toml
copypasta-ext = { version = "0.3.7", default-features = false, features = ["x11-fork", "wayland-bin"] }
```

**Review by orhun — APPROVED** [review]
Thanks for this awesome lib 💯

**Comment by orhun** [comment]
Do you think the next version should be `0.7.3` or `0.8.0` due to these changes? 😃

**Comment by timvisee** [comment]
> Do you think the next version should be `0.7.3` or `0.8.0` due to these changes? smiley

Good question. I'd assume `0.7.3` to be fine. It doesn't have breaking lib/API changes. But I don't know the exact semver rules.

**Comment by timvisee** [comment]
> Do you think the next version should be `0.7.3` or `0.8.0` due to these changes? smiley

Good question. I'd assume `0.7.3` to be fine. It doesn't have breaking lib/API changes. But I don't know the exact semver rules.

**Comment by timvisee** [comment]
The closest item from semver's FAQ seems to be: https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api

You change your own dependency, not your API. This doesn't explicitly cover what to do when your own dependency changes affect the required external dependencies. So I'm still not sure yet.

**Comment by orhun** [comment]
Yeah, I'm not sure either. I think I'm just gonna go with `0.7.3` and call it a day. I often do a minor bump when I add a new feature about TUI/GPG anyways.

**Pull request merged**
